export enum ValidateProfileError {
  INCORRECT_USER_DATA = 'INCORRECT_USER_DATA',
  INCORRECT_USER_AGE = 'INCORRECT_USER_AGE',
  INCORRECT_USER_USERNAME = 'INCORRECT_USER_USERNAME',
  NO_PROFILE_DATA = 'NO_PROFILE_DATA',
  SERVER_ERROR = 'SERVER_ERROR',
}
